import { z } from "zod";
import { ChatPromptTemplate } from "@langchain/core/prompts";
import { BaseChatModel } from "@langchain/core/language_models/chat_models";
import type { MatchResult } from "../types/api.js";

// Same schema shape as scoring-chain — weakMatch excluded (derived deterministically).
// contextPrompt is stripped from the output schema and reattached programmatically
// from the input after chain returns. The model must not regenerate it — it belongs
// to the scoring step and must be preserved exactly as the scoring chain produced it.
const MatchSchema = z.object({
  fitScore: z.number().min(0).max(100).describe("Semantic fit score from 0 to 100"),
  matchedSkills: z.array(z.string()).describe("Skills the candidate has that the job requires"),
  missingSkills: z.array(z.string()).describe("Required skills the candidate lacks"),
  narrativeAlignment: z.string().describe("How well the candidate's career narrative aligns with the role"),
  gaps: z.array(z.string()).describe("Specific gaps between the candidate's profile and the job requirements"),
  resumeAdvice: z
    .array(z.string())
    .describe("Specific, section-level resume suggestions referencing actual resume content. Empty array is correct when fitScore >= 75."),
  weakMatchReason: z
    .string()
    .optional()
    .describe("Explanation of why the match is weak, when fitScore < 60"),
});

const SYSTEM_PROMPT = `You are a senior career coach who specialises in resume tailoring.
Given a resume, job description, and match result between them, produce specific, actionable resume advice.
Each item in resumeAdvice must name a concrete resume section or bullet point to change,
referencing actual content from the resume where possible.
Return the full match result with resumeAdvice updated to contain these targeted, section-level suggestions.
Do not change fitScore, matchedSkills, missingSkills, narrativeAlignment, gaps, or weakMatchReason.`;

const HUMAN_PROMPT = `Resume Data:
{resume_data}

Job Data:
{job_data}

Match Result:
{match_result}

Rewrite the resumeAdvice in the match result with specific, section-level suggestions referencing actual resume content above.`;

export function buildGapAnalysisChain(model: BaseChatModel) {
  const prompt = ChatPromptTemplate.fromMessages([
    ["system", SYSTEM_PROMPT],
    ["human", HUMAN_PROMPT],
  ]);

  const structuredModel = model.withStructuredOutput(MatchSchema);

  return {
    invoke: async (input: {
      resume_data: string;
      job_data: string;
      match_result: string;
    }): Promise<MatchResult> => {
      if (!input.match_result) {
        throw new Error(
          "gap-analysis-chain: match_result is required — missing input indicates a graph wiring error"
        );
      }

      // Preserve fields that should not be regenerated by the model.
      // contextPrompt is from the scoring step and must be echoed unchanged.
      // weakMatch is derived deterministically (fitScore < 60); on parse failure
      // it is re-derived from the chain's returned fitScore so it stays consistent.
      let preservedContextPrompt: string | null = null;
      let parsedWeakMatch: boolean | null = null;
      try {
        const parsed = JSON.parse(input.match_result) as Partial<MatchResult>;
        preservedContextPrompt = parsed.contextPrompt ?? null;
        parsedWeakMatch = parsed.weakMatch ?? null;
      } catch {
        // logValidationFailure requires a ZodError — this is a JSON parse failure,
        // not a schema validation failure. console.error is the correct channel here.
        console.error("[gap-analysis] JSON.parse failed on match_result input", {
          nodeName: "gap-analysis",
          rawInput: input.match_result,
        });
        // parsedWeakMatch stays null — derived from fitScore after model call below
      }

      const messages = await prompt.invoke(input);
      const result = await structuredModel.invoke(messages, { runName: "gap-analysis" });

      const weakMatch = parsedWeakMatch !== null ? parsedWeakMatch : result.fitScore < 60;

      return {
        ...result,
        contextPrompt: preservedContextPrompt,
        weakMatch,
      } as MatchResult;
    },
  };
}
